<?php
/**
 * Creates the ACF field groups necessary for our plugin
 */

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5dc1f2ace21e1',
		'title' => 'PJS Staff Details',
		'fields' => array(
			array(
				'key' => 'field_5dc1f2ad12142',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Recommended size: 1400w x 1400h',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => 600,
				'min_height' => 600,
				'min_size' => '',
				'max_width' => 1400,
				'max_height' => 1400,
				'max_size' => '.5',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5dc1f30f4681c',
				'label' => 'Role',
				'name' => 'role',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc1f2ad0e437',
				'label' => 'Bio',
				'name' => 'bio',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 0,
				'delay' => 0,
			),
			array(
				'key' => 'field_5dc1f31f4681d',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc1f3284681e',
				'label' => 'Phone',
				'name' => 'phone',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc1f32f4681f',
				'label' => 'Facebook',
				'name' => 'facebook',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc1f33b46820',
				'label' => 'Twitter',
				'name' => 'twitter',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc1f34346821',
				'label' => 'Instagram',
				'name' => 'instagram',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc1f34746822',
				'label' => 'LinkedIn',
				'name' => 'linkedin',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'pjs_staff',
				),
			),
		),
		'menu_order' => -1,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5dc1d6bd8b956',
		'title' => 'PJS Staff Settings',
		'fields' => array(
			array(
				'key' => 'field_5dc1d6bd952b5',
				'label' => 'Slug',
				'name' => 'pjs_staff_slug',
				'type' => 'text',
				'instructions' => 'Slug used for the PJS Staff Manager.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33.3',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'media',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc1d6bd98fb7',
				'label' => 'Archive Title',
				'name' => 'pjs_staff_archive_title',
				'type' => 'text',
				'instructions' => 'Title used on the staff landing page for the staff list.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33.3',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc1d6bda09d4',
				'label' => 'View All Label',
				'name' => 'pjs_staff_view_all_label',
				'type' => 'text',
				'instructions' => 'Button label used to link back to the staff landing page.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33.3',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'View All Staff',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc1d6bda46ee',
				'label' => 'View Staff Member Label',
				'name' => 'pjs_staff_view_member_label',
				'type' => 'text',
				'instructions' => 'Button label used to link to the staff member page.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33.3',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'View Staff Member',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc1d6bda83e0',
				'label' => 'Load More Label',
				'name' => 'pjs_staff_load_more_label',
				'type' => 'text',
				'instructions' => 'Text used for the load more link on the staff landing page.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33.3',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'Load More',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc300f2b181b',
				'label' => 'Disable Bio Link',
				'name' => 'pjs_staff_disable_bio_link',
				'type' => 'true_false',
				'instructions' => 'If checked, this will disable linking to staff member pages on the archive page.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33.3',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-staff-settings',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;